---
layout: cv
title: Amelia Tuttle's CV
---
# Amelia Tuttle
Software Engineer Major | Member Experience Specialist

<div id="webaddress">
<a href="mailto:aetuttle@byui.edu">amelia.tuttle@example.com</a>
| <a href="https://www.linkedin.com/in/amelia-tuttle-1a0185255/">LinkedIn</a>
| <a href="https://github.com/ameliatuttle">GitHub</a>
</div>


## Currently

Final year Software Engineering major with a focus on full-stack development and data science.


### Specialized in

- Full-stack web development (JavaScript, React, Node.js)
- Software design patterns and testing
- User experience (UX) design and research

## Education

`Expected 2025`
__Brigham Young University | Idaho__, BS in Software Engineering

- Relevant coursework: Data Structures, Algorithm Design, Software Design, Web Development

## Experience

`2023 - Present`
__Member Experience Specialist__, Vasa

- Handle customer service questions
- Maintain gym

## Projects

`2024`
__Weather App__  
Created a full-stack weather application using React, Node.js, and the OpenWeather API.

`2023`
__E-commerce Platform__  
Developed a fully functional e-commerce platform as part of a team, focusing on product listings, shopping cart functionality, and order management.

## Skills

- Programming Languages: JavaScript, Python, HTML/CSS, C++, C#, C
- Frameworks: React, Node.js, Express
- Tools: Git, VS Code, Github

<!-- ### Footer

Last updated: December 2024 -->